### ISSUE TITLE
:C

### ISSUE THREAD

**Issue by TomasSalvadores** [TomasSalvadores/T07#29]
Traceback (most recent call last):
  File "C:\Users\William\Desktop\Programming\Programs\You wake up\main.py", line 16, in <module>
    import helper
  File "C:\Users\William\Desktop\Programming\Programs\You wake up\helper.py", line 13, in <module>
    import main
  File "C:\Users\William\Desktop\Programming\Programs\You wake up\main.py", line 103, in <module>
    init()
  File "C:\Users\William\Desktop\Programming\Programs\You wake up\main.py", line 41, in init
    game_text()
  File "C:\Users\William\Desktop\Programming\Programs\You wake up\main.py", line 77, in game_text
    helper.way_out_quest()
AttributeError: 'module' object has no attribute 'way_out_quest'

**Comment by TomasSalvadores** [comment]
Pueba revisando esto: https://stackoverflow.com/questions/19192209/attributeerror-module-object-has-no-attribute-utcnow
