### ISSUE TITLE
shsfgbs

### ISSUE THREAD

**Issue by NachoCasta** [TomasSalvadores/T07#43]
Traceback (most recent call last):
  File "C:\Users\******\Desktop\integrals.py", line 13, in <module>
    integral=integral+dx*f(n*dx)
  File "C:\Users\******\Desktop\integrals.py", line 3, in f
    f=math.sqrt(1+(6*x+4)^2)
TypeError: unsupported operand type(s) for ^: 'float' and 'int'

**Comment by TomasSalvadores** [comment]
Pueba revisando esto: https://stackoverflow.com/questions/34258537/python-typeerror-unsupported-operand-types-for-float-and-int

**Comment by NachoCasta** [comment]
gracias
