### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by sebacruzd** [TomasSalvadores/T07#44]
```
>>> 10 * (1/0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
>>> 4 + spam*3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
>>> '2' + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot concatenate 'str' and 'int' objects ```

**Comment by TomasSalvadores** [comment]
Pueba revisando esto: https://stackoverflow.com/questions/11844072/python-typeerror-cannot-concatenate-str-and-int-objects
